--Oracle DataBase
CREATE TABLE ARBITRO
  (
    cod_arb  SMALLINT NOT NULL ,
    nombre   VARCHAR2 (50) NOT NULL ,
    cod_pais SMALLINT NOT NULL
  ) ;
ALTER TABLE ARBITRO ADD CONSTRAINT ARBITRO_PK PRIMARY KEY ( cod_arb ) ;


CREATE TABLE ASIG
  (
    cod_arb     SMALLINT NOT NULL ,
    cod_partido INTEGER NOT NULL ,
    posicion    VARCHAR2 (15 CHAR)
  ) ;
ALTER TABLE ASIG ADD CONSTRAINT ASIG_PK PRIMARY KEY ( cod_arb, cod_partido ) ;


CREATE TABLE CIUDAD
  (
    cod_ciudad INTEGER NOT NULL ,
    nombre     VARCHAR2 (75 CHAR) NOT NULL
  ) ;
ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_PK PRIMARY KEY ( cod_ciudad ) ;


CREATE TABLE CONFEDERACION
  (
    cod      INTEGER NOT NULL ,
    nombre   VARCHAR2 (70 CHAR) NOT NULL ,
    acronimo VARCHAR2 (8) NOT NULL
  ) ;
ALTER TABLE CONFEDERACION ADD CONSTRAINT CONFEDERACION_PK PRIMARY KEY ( cod ) ;


CREATE TABLE EQUIPO
  (
    cod_equipo INTEGER NOT NULL ,
    director   VARCHAR2 (50 CHAR) NOT NULL ,
    cod_pais   SMALLINT NOT NULL ,
    grupo      CHAR (1 CHAR) NOT NULL
  ) ;
CREATE UNIQUE INDEX EQUIPO__IDX ON EQUIPO
  (
    cod_pais ASC
  )
  ;
ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO_PK PRIMARY KEY ( cod_equipo ) ;
ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO__UN UNIQUE ( cod_pais ) ;


CREATE TABLE JUGADOR
  (
    camiseta  SMALLINT NOT NULL ,
    fecha_nac DATE NOT NULL ,
    estatura FLOAT NOT NULL ,
    peso FLOAT NOT NULL ,
    nombre     VARCHAR2 (50 CHAR) NOT NULL ,
    equipo     VARCHAR2 (75 CHAR) ,
    posicion   VARCHAR2 (30 CHAR) NOT NULL ,
    cod_equipo INTEGER NOT NULL
  ) ;
ALTER TABLE JUGADOR ADD CONSTRAINT JUGADOR_PK PRIMARY KEY ( cod_equipo, camiseta ) ;


CREATE TABLE MARCADOR
  (
    goles         SMALLINT NOT NULL ,
    cod_equipo    INTEGER NOT NULL ,
    codigo_codigo INTEGER NOT NULL ,
    tipo          CHAR (1 CHAR) NOT NULL ,
    cod_usuario   INTEGER NOT NULL
  ) ;
ALTER TABLE MARCADOR ADD CONSTRAINT MARCADOR_PK PRIMARY KEY ( cod_usuario, codigo_codigo ) ;


CREATE TABLE PAIS
  (
    cod_pais SMALLINT NOT NULL ,
    nombre   VARCHAR2 (45) NOT NULL ,
    cod_conf INTEGER NOT NULL
  ) ;
ALTER TABLE PAIS ADD CONSTRAINT PAIS_PK PRIMARY KEY ( cod_pais ) ;


CREATE TABLE PARTIDO
  (
    codigo      INTEGER NOT NULL ,
    fecha       DATE NOT NULL ,
    hora_inicio DATE NOT NULL ,
    cod_ciudad  INTEGER NOT NULL
  ) ;
ALTER TABLE PARTIDO ADD CONSTRAINT PARTIDO_PK PRIMARY KEY ( codigo ) ;


CREATE TABLE RIVALES
  (
    cod_equipo     INTEGER NOT NULL ,
    codigo_partido INTEGER NOT NULL
  ) ;
ALTER TABLE RIVALES ADD CONSTRAINT RIVALES_PK PRIMARY KEY ( cod_equipo, codigo_partido ) ;


CREATE TABLE USUARIO
  (
    cod_usuario INTEGER NOT NULL ,
    nombre      VARCHAR2 (50) NOT NULL ,
    fecha_nac   DATE NOT NULL ,
    correo      VARCHAR2 (75) NOT NULL ,
    cod_pais    SMALLINT NOT NULL ,
    tipo        CHAR (1 CHAR) NOT NULL ,
    clave       VARCHAR2 (15 CHAR) NOT NULL ,
    pago        CHAR (1 CHAR) NOT NULL ,
    puntos      SMALLINT ,
    tipo_u      CHAR (1 CHAR) NOT NULL
  ) ;
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( cod_usuario ) ;
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO__correo UNIQUE ( correo ) ;


ALTER TABLE ARBITRO ADD CONSTRAINT ARBITRO_PAIS_FK FOREIGN KEY ( cod_pais ) REFERENCES PAIS ( cod_pais ) ;

ALTER TABLE ASIG ADD CONSTRAINT ASIG_ARBITRO_FK FOREIGN KEY ( cod_arb ) REFERENCES ARBITRO ( cod_arb ) ;

ALTER TABLE ASIG ADD CONSTRAINT ASIG_PARTIDO_FK FOREIGN KEY ( cod_partido ) REFERENCES PARTIDO ( codigo ) ;

ALTER TABLE EQUIPO ADD CONSTRAINT EQUIPO_PAIS_FK FOREIGN KEY ( cod_pais ) REFERENCES PAIS ( cod_pais ) ;

ALTER TABLE JUGADOR ADD CONSTRAINT JUGADOR_EQUIPO_FK FOREIGN KEY ( cod_equipo ) REFERENCES EQUIPO ( cod_equipo ) ;

ALTER TABLE MARCADOR ADD CONSTRAINT MARCADOR_EQUIPO_FK FOREIGN KEY ( cod_equipo ) REFERENCES EQUIPO ( cod_equipo ) ;

ALTER TABLE MARCADOR ADD CONSTRAINT MARCADOR_PARTIDO_FK FOREIGN KEY ( codigo_codigo ) REFERENCES PARTIDO ( codigo ) ;

ALTER TABLE MARCADOR ADD CONSTRAINT MARCADOR_USUARIO_FK FOREIGN KEY ( cod_usuario ) REFERENCES USUARIO ( cod_usuario ) ;

ALTER TABLE PAIS ADD CONSTRAINT PAIS_CONFEDERACION_FK FOREIGN KEY ( cod_conf ) REFERENCES CONFEDERACION ( cod ) ;

ALTER TABLE PARTIDO ADD CONSTRAINT PARTIDO_CIUDAD_FK FOREIGN KEY ( cod_ciudad ) REFERENCES CIUDAD ( cod_ciudad ) ;

ALTER TABLE RIVALES ADD CONSTRAINT RIVALES_EQUIPO_FK FOREIGN KEY ( cod_equipo ) REFERENCES EQUIPO ( cod_equipo ) ;

ALTER TABLE RIVALES ADD CONSTRAINT RIVALES_PARTIDO_FK FOREIGN KEY ( codigo_partido ) REFERENCES PARTIDO ( codigo ) ;

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PAIS_FK FOREIGN KEY ( cod_pais ) REFERENCES PAIS ( cod_pais ) ;

CREATE SEQUENCE ARBITRO_cod_arb_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER ARBITRO_cod_arb_TRG BEFORE
  INSERT ON ARBITRO FOR EACH ROW WHEN (NEW.cod_arb IS NULL) BEGIN :NEW.cod_arb := ARBITRO_cod_arb_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE CONFEDERACION_cod_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER CONFEDERACION_cod_TRG BEFORE
  INSERT ON CONFEDERACION FOR EACH ROW WHEN (NEW.cod IS NULL) BEGIN :NEW.cod := CONFEDERACION_cod_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE EQUIPO_cod_equipo_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER EQUIPO_cod_equipo_TRG BEFORE
  INSERT ON EQUIPO FOR EACH ROW WHEN (NEW.cod_equipo IS NULL) BEGIN :NEW.cod_equipo := EQUIPO_cod_equipo_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE PAIS_cod_pais_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER PAIS_cod_pais_TRG BEFORE
  INSERT ON PAIS FOR EACH ROW WHEN (NEW.cod_pais IS NULL) BEGIN :NEW.cod_pais := PAIS_cod_pais_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE PARTIDO_codigo_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER PARTIDO_codigo_TRG BEFORE
  INSERT ON PARTIDO FOR EACH ROW WHEN (NEW.codigo IS NULL) BEGIN :NEW.codigo := PARTIDO_codigo_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE USUARIO_cod_usuario_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER USUARIO_cod_usuario_TRG BEFORE
  INSERT ON USUARIO FOR EACH ROW WHEN (NEW.cod_usuario IS NULL) BEGIN :NEW.cod_usuario := USUARIO_cod_usuario_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE CIUDAD_cod_ciudad_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Ciudad_cod_ciudad_TRG BEFORE
  INSERT ON CIUDAD FOR EACH ROW WHEN (NEW.cod_ciudad IS NULL) BEGIN :NEW.cod_ciudad := CIUDAD_cod_ciudad_SEQ.NEXTVAL;
END;
/
